// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Airport.Models
{
    public partial class Airline
    {
        [Key]
        public int Airline_ID { get; set; }

        public string Airline_Name { get; set; }

        public string Country { get; set; }

        public int Airplane_Count { get; set; }

        public string Type { get; set; }

        public virtual ICollection<Airplane> Airplanes { get; set; } = new List<Airplane>();

        public virtual ICollection<Flight> Flights { get; set; } = new List<Flight>();
    }
}
