// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Airport.Models
{
    [Table("Airplane")]
    public partial class Airplane
    {
        [Key]
        public int Airplane_ID { get; set; }

        public int Seat_Count { get; set; }

        public string Board_Number { get; set; }

        public int Flight_Range { get; set; }

        public int Ticket_Price_Class { get; set; }

        public int Airline_ID { get; set; }

        public virtual Airline Airline { get; set; }

        public virtual ICollection<CrewMember> CrewMembers { get; set; } = new List<CrewMember>();

        public virtual ICollection<Flight> Flights { get; set; } = new List<Flight>();

        public virtual ICollection<Passenger> Passengers { get; set; } = new List<Passenger>();
    }
}
