// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Airport.Models
{
    [Table("Flights")]
    public partial class Flight
    {
        [Key]
        public int Flight_ID { get; set; }

        public TimeSpan Departure_Time { get; set; }

        public DateTime Arrival_Date_Time { get; set; }

        public int Airline_ID { get; set; }

        public int Airplane_ID { get; set; }

        public virtual Airline Airline { get; set; }

        public virtual Airplane Airplane { get; set; }
    }
}
