// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;

namespace Airport.Models
{
    public partial class Ticket
    {
        [Key]
        public int Ticket_ID { get; set; }
        public int Ticket_Price { get; set; }
        public string Ticket_Class { get; set; }
        public DateTime Purchase_Date_Time { get; set; }
        public int Passenger_ID { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
